### ISSUE TITLE
plugin install

### ISSUE THREAD

**Issue by john-livelyvideo** [salesforce/helm-starter-istio#36]
0VEMD6M:istio jdavis$ helm plugin install https://github.com/salesforce/helm-starter.git
Installed plugin: starter
0VEMD6M:istio jdavis$ helm starter fetch https://github.com/salesforce/helm-starter-istio.git
/Users/jdavis/Library/helm/plugins/helm-starter.git/starter.sh: line 56: cd: /Users/jdavis/Library/helm/starters: No such file or directory
Error: plugin "starter" exited with error

creating the dir fixes it

**Comment by rmichela** [comment]
Thanks! Fixed in `helm-starter` plugin.
